apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: default
spec:
  clusterIP: None        # Headless = ไม่มี load balance, DNS ชี้ตรง Pod
  selector:
    app: web
  ports:
  - port: 80
    name: web
