apiVersion: v1
kind: ConfigMap
metadata:
  name: fastapi-config
  namespace: level5
data:
  APP_ENV: "development"
  LOG_LEVEL: "info"
  APP_PORT: "8000"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "appdb"
