apiVersion: v1
kind: Secret
metadata:
  name: fastapi-secret
  namespace: level5
type: Opaque
data:
  # Generate with: echo -n 'yourvalue' | base64
  DB_USER: <base64_encoded_value>
  DB_PASSWORD: <base64_encoded_value>
  SECRET_KEY: <base64_encoded_value>
