name: Docker CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 1 Checkout repo
        uses: actions/checkout@v4

      - name: 2 Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

<<<<<<< HEAD
      - name: Build Docker image
        run: docker build -t devops-api -f docker/Dockerfile .
=======
      - name: 3 Build Docker image
        run: docker build -t devops-api -f docker/Dockerfile .

      - name: 4 Test docker image
        run: docker images
>>>>>>> 47792fd (Add GitHub Actions CI)
